dream:
  auth:
    kafka-supported: false
    app:
      name: Dream
      title: Dream
      formatted-version: 1.0.0
      issuer: CN=ConSec,CN=COM,CN=SH
    server:
      scheme: http
      domain: ${SERVER_DOMAIN:dream.top}
      sub-domain: sso.${dream.auth.server.domain}
      name: ${dream.auth.server.scheme}://${dream.auth.server.domain.sub}
      uri: ${dream.auth.server.name}/dream
      default-uri: ${dream.auth.server.uri}/dream/appList
      mgt-uri: ${dream.auth.server.name}:9521/dream-mgt/login
    login:
      default-uri: appList
      captcha:
        enabled: ${LOGIN_CAPTCHA:true}
        # text or arithmetic
        type: text
      mfa:
        # enable two factor,use one time password
        enabled: true
        # TimeBasedOtpAuthn MailOtpAuthn SmsOtpAuthnYunxin SmsOtpAuthnAliyun SmsOtpAuthnTencentCloud
        type: TimeBasedOtpAuthn
      social-sign:
        providers: sinaweibo,google,qq,dingtalk,microsoft,facebook
      kerberos: 
        enabled: true
        # short name of user domain must be in upper case,eg:DREAM
        default-user-domain: DREAM
        # short name of user domain must be in upper case,eg:DREAM.ORG
        default-full-user-domain: DREAM.ORG
        # last 8Bit crypto for Kerberos web Authentication 
        default-crypto: 846KZSzYq56M6d5o
        # Kerberos Authentication server RUL
        default-redirect-uri: http://sso.dream.top/kerberos/authn/
      http-header:
        enabled: false
        header-name: header-user
      basic:
        enabled: false
      ws-federation: 
        enabled: false
        identifier: http://adfs.dream.top/adfs/services/trust
        url: https://adfs.dream.top/adfs/ls/
        principal: upn
        relying-party: urn:federation:connsec
        signing-certificate: adfs-signing.crt
        tolerance: 10000
        upn-suffix: dream.org
        logout-url: https://adfs.dream.top/adfs/ls/?wa=wsignout1.0
    ip:
      white: false
    oidc:
      metadata:
        issuer: ${dream.auth.server.name}/dream
        authorization-endpoint: ${dream.auth.server.name}/dream/authz/oauth/v20/authorize
        token-endpoint: ${dream.auth.server.name}/dream/authz/oauth/v20/token
        userinfo-endpoint: ${dream.auth.server.name}/dream/api/connect/userinfo