server: 
  ssl:
    enabled: true
    key-alias: dream
    key-store: dreamserver.keystore
    key-store-password: dream
    key-store-type: JKS
    
spring:
  application:
    name: dream-test-auth2-persistence

mybatis-plus:
  type-aliases-package: com.wy.test.core.entity,com.wy.test.core.vo,com.wy.test.core.query
  mapper-locations:
  - classpath*:mapper/*.xml