server: 
  port: 5550
  servlet:
    context-path: /dream
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  ssl:
    enabled: true
    key-alias: dream
    key-store: dreamserver.keystore
    key-store-password: dream
    key-store-type: JKS
    
spring:
  application:
    name: cloud-security
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dream_auth?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  profiles: 
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 4194304
  redis:
    host: localhost
    port: 6379
    password: password
    timeout: 10000
    jedis:
      pool:
        max-wait: 1000
        max-idle: 200
    lettuce:
      pool: 
        max-active: -1
        min-idle: 0
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    port: 465
    username: dream@163.com
    password: password
    protocol: smtp
    properties:
      ssl: true
      sender: dream@163.com
      mailotp-message-subject: dream One Time PassWord
      mailotp-message-template: "{0} You Token is {1} , it validity in {2}  minutes."

  freemarker:
    template-loader-path: classpath:/templates/views
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl

  messages:
    basename: classpath:messages/message
    encoding: UTF-8

  main:
    banner-mode: log
    allow-bean-definition-overriding: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 0
      acks: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
          ms: 0

mybatis:
  type-aliases-package: com.wy.test.core.entity,com.wy.test.core.vo,com.wy.test.core.query
  mapper-locations:
  - classpath*:mapper/*.xml