dream:
  auth:
    saml:
      max-parser-pool-size: 2
      assertion:
        validity-time-in-seconds: 90
      replay:
        cache-life-in-millis: 14400000
      issue:
        instant-check-clock-skew-in-seconds: 90
        instant-check-validity-time-in-seconds: 300
      idp:
        keystore-password: dream
        keystore-private-key-password: dream
        issuing-entity-id: dream.top
        issuer: https://sso.dream.top/dream/saml
        receiver-endpoint: https://sso.dream.top/
      sp:
        keystore-password: dream
        keystore-private-key-password: dream
        issuing-entity-id: client.dream.top
      metadata:
          org-name: dream
          org-display-name: dream
          org-url: https://github.com/shimingxy/dream
          contact-type: technical
          company: dream
          given-name: dream
          sur-name: dream
          email: shimingxy@163.com
          phone-number: 4008981111