dream:
  auth:
    kafka-supported: false
    app:
      name: dream
      title: dream
      version: 1.0.0
      issuer: CN=ConSec,CN=COM,CN=SH
    server:
      scheme: http
      domain: ${SERVER_DOMAIN:dream.top}
      sub-domain: sso.${dream.auth.server.domain}
      name: ${dream.auth.server.scheme}://${dream.auth.server.sub-domain}
#      uri: ${dream.auth.server.name}:${server.port}${server.servlet.context-path}
      default-uri: ${dream.auth.server.uri}/dream/appList
      mgt-uri: ${dream.auth.server.name}:9521/dream-mgt/login
#      authz-uri: ${dream.auth.server.name}:${server.port}${server.servlet.context-path}
      authz-uri: ${dream.auth.server.name}:${server.port}
      store-type: ${SERVER_PERSISTENCE:inmemory}
      provision: ${SERVER_PROVISION:false}
      frontend-port: ${SERVER_FRONTEND_PORT:4200}
      frontend-uri: /dream
    jwk:
      issuer: ${dream.auth.server.default-uri}
      secret: 7heM-14BtxjyKPuH3ITIm7q2-ps5MuBirWCsrrdbzzSAOuSPrbQYiaJ54AeA0uH2XdkYy3hHAkTFIsieGkyqxOJZ_dQzrCbaYISH9rhUZAKYx8tUY0wkE4ArOC6LqHDJarR6UIcMsARakK9U4dhoOPO1cj74XytemI-w6ACYfzRUn_Rn4e-CQMcnD1C56oNEukwalf06xVgXl41h6K8IBEzLVod58y_VfvFn-NGWpNG0fy_Qxng6dg8Dgva2DobvzMN2eejHGLGB-x809MvC4zbG7CKNVlcrzMYDt2Gt2sOVDrt2l9YqJNfgaLFjrOEVw5cuXemGkX1MvHj6TAsbLg
      refresh-secret: 7heM-14BtxjyKPuH3ITIm7q2-ps5MuBirWCsrrdbzzSAOuSPrbQYiaJ54AeA0uH2XdkYy3hHAkTFIsieGkyqxOJZ_dQzrCbaYISH9rhUZAKYx8tUY0wkE4ArOC6LqHDJarR6UIcMsARakK9U4dhoOPO1cj74XytemI-w6ACYfzRUn_Rn4e-CQMcnD1C56oNEukwalf06xVgXl41h6K8IBEzLVod58y_VfvFn-NGWpNG0fy_Qxng6dg8Dgva2DobvzMN2eejHGLGB-x809MvC4zbG7CKNVlcrzMYDt2Gt2sOVDrt2l9YqJNfgaLFjrOEVw5cuXemGkX1MvHj6TAsbLg
      expires: 600
    crypto:
      password-type: bcrypt
      
    ip:
      white: false
    notice:
      visible: false
      
    oidc:
      metadata:
        issuer: ${dream.auth.server.authz-uri}
#        issuer: ${dream.auth.server.name}/dream
        authorization-endpoint: ${dream.auth.server.authz-uri}/authz/oauth/v20/authorize
#        authorization-endpoint: ${dream.auth.server.name}/dream/authz/oauth/v20/authorize
        token-endpoint: ${dream.auth.server.authz-uri}/authz/oauth/v20/token
#        token-endpoint: ${dream.auth.server.name}/dream/authz/oauth/v20/token
        userinfo-endpoint: ${dream.auth.server.authz-uri}/api/connect/userinfo
#        userinfo-endpoint: ${dream.auth.server.name}/dream/api/connect/userinfo

    swagger:
      enabled: true
      title: 单点登录认证系统API文档
      description: 单点登录认证系统API文档
      version: ${dream.auth.app.version}
