dream:
  auth:
    login:
      default-uri: appList
      captcha:
        enabled: ${LOGIN_CAPTCHA:false}
        # text or arithmetic
        type: text
      mfa:
        enabled: ${LOGIN_MFA_ENABLED:true}
        # TimeBasedOtpAuthn MailOtpAuthn SmsOtpAuthnYunxin SmsOtpAuthnAliyun SmsOtpAuthnTencentCloud
        type: ${LOGIN_MFA_TYPE:TimeBasedOtpAuthn}
      social-sign:
        enabled: ${LOGIN_SOCIAL_ENABLED:true}
        providers: sinaweibo,google,qq,dingtalk,microsoft,facebook
      kerberos: 
        enabled: false
        default-user-domain: DREAM
        default-full-user-domain: DREAM.ORG
        default-crypto: 846KZSzYq56M6d5o
        default-redirect-uri: http://sso.dream.top/kerberos/authn/
      http-header:
        enabled: false
        header-name: header-user
      basic:
        enabled: false
      ws-federation: 
        enabled: false
        identifier: http://adfs.dream.top/adfs/services/trust
        url: https://adfs.dream.top/adfs/ls/
        principal: upn
        relying-party: urn:federation:connsec
        signing-certificate: adfs-signing.crt
        tolerance: 10000
        upn-suffix: dream.org
        logout-url: https://adfs.dream.top/adfs/ls/?wa=wsignout1.0
      jwt:
        enabled: ${LOGIN_JWT:true}
        issuer: ${LOGIN_JWT_ISSUER:${dream.auth.server.authz-uri}}
      remember-me: ${LOGIN_REMEBERME:true}
      remember-me-validity: 0