dream:
  auth:
    otp:
      policy:
        type: totp
        digits: 6
        issuer: ${OTP_POLICY_ISSUER:dream}
        domain: ${dream.auth.server.domain}
        period: 30
      sms:
        # SmsOtpAuthnYunxin SmsOtpAuthnAliyun SmsOtpAuthnTencentCloud
        class-name: "com.wy.test.sms.password.sms.impl.SmsOtpAuthnYunxin"
        aliyun:
          accesskeyid: 94395d754eb55693043f5d6a2b772ef4
          accesssecret: 05d5485357bc
          templatecode: 14860095
          signname: dream
        yunxin:
          appkey: 94395d754eb55693043f5d6a2b772ef4
          appsecret: 05d5485357bc
          templateid: 14860095
        tencentcloud:
          secretid: 94395d754eb55693043f5d6a2b772ef4
          secretkey: 05d5485357bc
          smssdkappid: 1486220095
          templateid: 14860095
          sign: 1486009522
      keyuri:
        type: totp
        digits: 6
        issuer: dream
        domain: ${dream.auth.server.domain}
        period: 30