server:
  port: ${SERVER_PORT:9527}
  servlet:
    context-path: /sign
    session:
      timeout: ${SERVLET_SESSION_TIMEOUT:600}
    encoding:
      enabled: true
      force: true
      charset: UTF-8

debug: true
spring:
  application:
    name: dream
  main:
    banner-mode: log
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/
  profiles:
    active: ${SERVER_PROFILES:config}
  servlet:
    multipart:
      enabled: true
      max-file-size: 4194304
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dream_auth?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PWD:123456}
  redis:
    host: localhost
    password: password
    timeout: 10000
    jedis:
      pool:
        max-wait: 1000
        max-idle: 200
    lettuce:
      pool: 
        max-active: -1
        min-idle: 0
  mail:
    default-encoding: utf-8
    host: ${MAIL_HOST:smtp.163.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USER:dream@163.com}
    password: ${MAIL_PWD:password}
    protocol: smtp
    properties:
      ssl: true
      sender: ${MAIL_SENDER:dream@163.com}
      mailotp:
        message:
          subject: Dream One Time PassWord
          template: "{0} You Token is {1} , it validity in {2}  minutes."
          type: html
          validity: 300
#        mailotp-message-subject: Dream One Time PassWord
#      mailotp-message-template: "{0} You Token is {1} , it validity in {2}  minutes."
#      mailotp-message-type: html
#      mailotp-message-validity: 300

  messages:
    basename: classpath:messages/message
    encoding: UTF-8

  freemarker:
    template-loader-path: classpath:/templates/views/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
      
  boot:
    admin:
      client:
        enabled: ${SPRING_BOOT_ADMIN_ENABLED:false}
        url: ${SPRING_BOOT_ADMIN_URL:http://127.0.0.1:9528}
        username: ${SPRING_BOOT_ADMIN_USERNAME:}
        password: ${SPRING_BOOT_ADMIN_PASSWORD:}

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include:
        - health
        - info
  endpoint:
    health:
      show-details: ALWAYS
  health:
      redis:
        enabled: false
      mail:
        enabled: false

#mybatis-plus:
#  type-aliases-package: com.wy.test.core.entity,com.wy.test.core.vo,com.wy.test.core.query
#  mapper-locations:
#  - classpath*:mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs: 
    - group: default
      paths-to-match: /*
      packages-to-scan: org.dream
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: "实体类列表"