server:
  port: 9000

spring:
  application:
    name: dream-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: dream_route
          uri: lb://dream
          filters:
            - PrefixPath=/
          predicates:
            - Path=/sign/**
        - id: dream_mgt_route
          uri: lb://dream-mgt
          filters:
            - PrefixPath=/
          predicates:
            - Path=/dream-mgt-api/**

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            #1分钟服务无响应则直接熔断
            timeoutInMilliseconds: 60000
            