#端口号
application:
  name: dream-gateway-server
  formatted-version: v3.5.15 GA
server:
  port: 9000
spring:
  application:
    name: dream-gateway
  cloud:
    gateway:
      routes:
#nacos健康检查端口8080
        - id: dreams_route
          uri: lb://dream
          filters:
            - PrefixPath=/
          predicates:
            - Path=/sign/**
        - id: dream_mgts_route
          uri: lb://dream-mgt
          filters:
            - PrefixPath=/
          predicates:
            - Path=/dream-mgt-api/**
#      default-filters:
#       - name: Hystrix
#          args:
#            name: default
#            fallbackUri: 'forward:/defaultFallback'
        
  main:
    web-application-type: reactive
#spring.main.web-application-type=reactive
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            #1分钟服务无响应则直接熔断
            timeoutInMilliseconds: 60000
            