dream:
  auth:
    app:
      title: Dream-Mgt
      version: 1.0.0
    server:
      scheme: http
      base-domain: ${SERVER_DOMAIN:dream.top}
      domain: sso.${dream.auth.server.basedomain}
      name: ${dream.auth.server.scheme}://${dream.auth.server.domain}
      uri: ${dream.auth.server.name}:${server.port}${server.servlet.context-path}
      default-uri: ${dream.auth.server.uri}/main
      mgt-uri: ${dream.auth.server.uri}
      authz-uri: https://${dream.auth.server.domain}/dream
      provision: ${SERVER_PROVISION:false}
    jwk:
      issuer: ${dream.auth.server.uri}
      expires: 900
      secret: 7heM-14BtxjyKPuH3ITIm7q2-ps5MuBirWCsrrdbzzSAOuSPrbQYiaJ54AeA0uH2XdkYy3hHAkTFIsieGkyqxOJZ_dQzrCbaYISH9rhUZAKYx8tUY0wkE4ArOC6LqHDJarR6UIcMsARakK9U4dhoOPO1cj74XytemI-w6ACYfzRUn_Rn4e-CQMcnD1C56oNEukwalf06xVgXl41h6K8IBEzLVod58y_VfvFn-NGWpNG0fy_Qxng6dg8Dgva2DobvzMN2eejHGLGB-x809MvC4zbG7CKNVlcrzMYDt2Gt2sOVDrt2l9YqJNfgaLFjrOEVw5cuXemGkX1MvHj6TAsbLg
      refresh-secret: 7heM-14BtxjyKPuH3ITIm7q2-ps5MuBirWCsrrdbzzSAOuSPrbQYiaJ54AeA0uH2XdkYy3hHAkTFIsieGkyqxOJZ_dQzrCbaYISH9rhUZAKYx8tUY0wkE4ArOC6LqHDJarR6UIcMsARakK9U4dhoOPO1cj74XytemI-w6ACYfzRUn_Rn4e-CQMcnD1C56oNEukwalf06xVgXl41h6K8IBEzLVod58y_VfvFn-NGWpNG0fy_Qxng6dg8Dgva2DobvzMN2eejHGLGB-x809MvC4zbG7CKNVlcrzMYDt2Gt2sOVDrt2l9YqJNfgaLFjrOEVw5cuXemGkX1MvHj6TAsbLg
    login:
      captcha: 
        enabled: ${LOGIN_CAPTCHA:true}
      mfa: 
        enabled: false
      ws-federation: 
        enabled: false
      remember-me: false
      remember-me-validity: 0
      kerberos: 
        enabled: false
      jwt:
        enabled: ${LOGIN_JWT:true}
        issuer: ${LOGIN_JWT_ISSUER:${dream.server.authz.uri}}
    ip:
      white: false
    otp:
      policy:
        type: totp
        digits: 6
        issuer: ${OTP_POLICY_ISSUER:dream}
        domain: ${dream.server.domain}
        period: 30
    oidc:
      metadata:
        issuer: ${dream.auth.server.authz.uri}
        authorization-endpoint: ${dream.auth.server.authz-uri}/authz/oauth/v20/authorize
        token-endpoint: ${dream.auth.server.authz-uri}/authz/oauth/v20/token
        userinfo-endpoint: ${dream.auth.server.authz-uri}/api/connect/userinfo
    saml:
      max-parser-pool-size: 2
      replay:
        cache-life-in-millis: 14400000
      metadata:
        org-name: dreamTop
        org-display-name: dreamTop
        org-url: https://www.dream.top
        contact-type: technical
        company: dreamTop
        given-name: dream
        sur-name: dream
        email: mygodness30@sina.com
        phone-number: 4008981111
      idp:
        issuer: ${dream.server.authz.uri}/saml
        receiver-endpoint: https://sso.dream.top/
#        keystore: classpath:config/samlServerKeystore.jks
        issuing-entity-id: dream.top
      issue:
          instant-check-clock-skew-in-seconds: 90
          instant-check-validity-time-in-seconds: 300
      assertion:
        validity-time-in-seconds: 90
      sp:
#        keystore: classpath:config/samlClientKeystore.jks
        issuing-entity-id: client.dream.org
    job:
      cron:
        enabled: true
        schedule: 0 0 0/1 * * ?
    swagger:
      enabled: true
      title: 单点登录认证系统API文档
      description: 单点登录认证系统API文档
      version: ${dream.auth.app.version}
    mybatis:
      dialect: mysql
      table-column-snowflake-datacenter-id: 1
      table-column-snowflake-machine-id: 1