dream:
  auth:
    app:
      title: dream
      formatted-version: 1.0.0
      issuer: CN=ConSec,CN=COM,CN=SH
    server:
      scheme: http
      domain: ${SERVER_DOMAIN:dream.top}
      sub-domain: sso.${dream.auth.server.domain}
      name: ${dream.auth.server.scheme}://${dream.auth.server.domain.sub}
      uri: ${dream.auth.server.name}:${server.port}${server.servlet.context-path}
      default-uri: ${dream.auth.server.uri}/dream/appList
      mgt-uri: ${dream.auth.server.name}:9521/dream-mgt/login
      authz-uri: ${dream.auth.server.name}:${server.port}${server.servlet.context-path}
      store-type: ${SERVER_PERSISTENCE:0}
      provision: ${SERVER_PROVISION:false}
      frontend-port: ${SERVER_FRONTEND_PORT:4200}
      frontend-uri: /dream
    jwk:
      issuer: ${dream.auth.server.uri}
      secret: 7heM-14BtxjyKPuH3ITIm7q2-ps5MuBirWCsrrdbzzSAOuSPrbQYiaJ54AeA0uH2XdkYy3hHAkTFIsieGkyqxOJZ_dQzrCbaYISH9rhUZAKYx8tUY0wkE4ArOC6LqHDJarR6UIcMsARakK9U4dhoOPO1cj74XytemI-w6ACYfzRUn_Rn4e-CQMcnD1C56oNEukwalf06xVgXl41h6K8IBEzLVod58y_VfvFn-NGWpNG0fy_Qxng6dg8Dgva2DobvzMN2eejHGLGB-x809MvC4zbG7CKNVlcrzMYDt2Gt2sOVDrt2l9YqJNfgaLFjrOEVw5cuXemGkX1MvHj6TAsbLg
      refresh-secret: 7heM-14BtxjyKPuH3ITIm7q2-ps5MuBirWCsrrdbzzSAOuSPrbQYiaJ54AeA0uH2XdkYy3hHAkTFIsieGkyqxOJZ_dQzrCbaYISH9rhUZAKYx8tUY0wkE4ArOC6LqHDJarR6UIcMsARakK9U4dhoOPO1cj74XytemI-w6ACYfzRUn_Rn4e-CQMcnD1C56oNEukwalf06xVgXl41h6K8IBEzLVod58y_VfvFn-NGWpNG0fy_Qxng6dg8Dgva2DobvzMN2eejHGLGB-x809MvC4zbG7CKNVlcrzMYDt2Gt2sOVDrt2l9YqJNfgaLFjrOEVw5cuXemGkX1MvHj6TAsbLg
      expires: 600
    crypto:
      password-type: bcrypt
      
    login:
      default-uri: appList
      captcha:
        enabled: ${LOGIN_CAPTCHA:false}
      mfa:
        enabled: ${LOGIN_MFA_ENABLED:true}
        # TimeBasedOtpAuthn MailOtpAuthn SmsOtpAuthnYunxin SmsOtpAuthnAliyun SmsOtpAuthnTencentCloud
        type: ${LOGIN_MFA_TYPE:TimeBasedOtpAuthn}
      social-sign:
        enabled: ${LOGIN_SOCIAL_ENABLED:true}
        providers: sinaweibo,google,qq,dingtalk,microsoft,facebook
      kerberos: 
        enabled: false
        default-user-domain: DREAM
        default-full-user-domain: DREAM.ORG
        default-crypto: 846KZSzYq56M6d5o
        default-redirect-uri: http://sso.dream.top/kerberos/authn/
      http-header:
        enabled: false
        header-name: header-user
      basic:
        enabled: false
      ws-federation: 
        enabled: false
        identifier: http://adfs.dream.top/adfs/services/trust
        url: https://adfs.dream.top/adfs/ls/
        principal: upn
        relying-party: urn:federation:connsec
        signing-certificate: adfs-signing.crt
        tolerance: 10000
        upn-suffix: dream.org
        logout-url: https://adfs.dream.top/adfs/ls/?wa=wsignout1.0
      remember-me: ${LOGIN_REMEBERME:true}
      remember-me-validity: 0
      jwt:
        enabled: ${LOGIN_JWT:true}
        issuer: ${LOGIN_JWT_ISSUER:${dream.auth.server.authz-uri}}
    ip:
      white: false
    notice:
      visible: false
      
    otp:
      policy:
        type: totp
        digits: 6
        issuer: ${OTP_POLICY_ISSUER:dream}
        domain: ${dream.auth.server.domain}
        period: 30

    oidc:
      metadata:
        issuer: ${dream.auth.server.authz-uri}
        authorization-endpoint: ${dream.auth.server.authz-uri}/authz/oauth/v20/authorize
        token-endpoint: ${dream.auth.server.authz-uri}/authz/oauth/v20/token
        userinfo-endpoint: ${dream.auth.server.authz-uri}/api/connect/userinfo

    swagger:
      enabled: true
      title: 单点登录认证系统API文档
      description: 单点登录认证系统API文档
      version: ${dream.auth.app.formatted-version}
