server:
  port: 55556
  servlet:
    context-path: /test

#logging:
#  level:
#    '[org.zalando.logbook]': trace
#    '[org.flywaydb]': debug

spring:
  application:
    name: test
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dream_auth?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&&allowPublicKeyRetrieval=true
    username: root
    password: 123456
#  flyway:
#    # 首次迁移时基线化非空数据库
#    baseline-on-migrate: true