CREATE TABLE IF NOT EXISTS sys_operation_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    trace_id VARCHAR(64) COMMENT '链路追踪ID',
    app_name VARCHAR(64) COMMENT '应用名称',
    module VARCHAR(64) COMMENT '模块名称',
    operation_type VARCHAR(32) COMMENT '操作类型',
    operation_desc VARCHAR(512) COMMENT '操作描述',
    method_name VARCHAR(256) COMMENT '方法名',
    class_name VARCHAR(256) COMMENT '类名',
    package_name VARCHAR(256) COMMENT '包名',
    request_url VARCHAR(1024) COMMENT '请求URL',
    request_method VARCHAR(16) COMMENT '请求方法',
    request_params TEXT COMMENT '请求参数',
    request_body LONGTEXT COMMENT '请求体',
    request_headers TEXT COMMENT '请求头',
    request_time DATETIME COMMENT '请求时间',
    response_status INT COMMENT '响应状态码',
    response_body LONGTEXT COMMENT '响应内容',
    response_headers TEXT COMMENT '响应头',
    response_time DATETIME COMMENT '响应时间',
    cost_time BIGINT COMMENT '耗时(毫秒)',
    success TINYINT(1) COMMENT '是否成功',
    error_msg TEXT COMMENT '错误信息',
    client_ip VARCHAR(64) COMMENT '客户端IP',
    user_id VARCHAR(64) COMMENT '用户ID',
    username VARCHAR(64) COMMENT '用户名',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_trace_id (trace_id),
    INDEX idx_app_name (app_name),
    INDEX idx_created_time (created_time),
    INDEX idx_operation_type (operation_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统操作日志表'; 